---
# tasks file for neutron

- name: Create database for keystone
  mysql_db: login_host=localhost login_user=root login_password={{ mysql_root_password }} name=neutron state=present

- name: Create keystone database user and assign privileges
  mysql_user: login_host=localhost login_user=root login_password={{ mysql_root_password }} name=neutron password={{ neutrondb_password }} priv='*.*:ALL' host={{ item }} state=present
  with_items:
    - localhost
    - '%'

- name: Install neutron packages on node
  apt: name={{ item }} state=present force=yes
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent
  when: ansible_os_family == "Debian"

- name: Update the neutron.conf file
  ini_file: dest=/etc/neutron/neutron.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'core_plugin', value: 'ml2' }
    - { section: 'DEFAULT', option: 'service_plugins', value: 'router' }
    - { section: 'DEFAULT', option: 'allow_overlapping_ips', value: 'True' }
    - { section: 'DEFAULT', option: 'rpc_backend', value: 'rabbit' }
    - { section: 'DEFAULT', option: 'auth_strategy', value: 'keystone' }
    - { section: 'DEFAULT', option: 'notify_nova_on_port_status_changes', value: 'True' }
    - { section: 'DEFAULT', option: 'notify_nova_on_port_data_changes', value: 'True' }
    - { section: 'database', option: 'connection', value: 'mysql+pymysql://neutron:{{ neutrondb_password }}@localhost/neutron' }
    - { section: 'oslo_messaging_rabbit', option: 'rabbit_host', value: 'localhost' }
    - { section: 'oslo_messaging_rabbit', option: 'rabbit_userid', value: 'openstack' }
    - { section: 'oslo_messaging_rabbit', option: 'rabbit_password', value: "{{ rabbitmq_password }}" }
    - { section: 'keystone_authtoken', option: 'auth_uri', value: 'http://localhost:5000' }
    - { section: 'keystone_authtoken', option: 'auth_url', value: 'http://localhost:35357' }
    - { section: 'keystone_authtoken', option: 'memcached_servers', value: 'localhost:11211' }
    - { section: 'keystone_authtoken', option: 'auth_type', value: 'password' }
    - { section: 'keystone_authtoken', option: 'project_domain_name', value: 'default' }
    - { section: 'keystone_authtoken', option: 'user_domain_name', value: 'default' }
    - { section: 'keystone_authtoken', option: 'project_name', value: 'service' }
    - { section: 'keystone_authtoken', option: 'username', value: 'neutron' }
    - { section: 'keystone_authtoken', option: 'password', value: "{{ serviceuser_password }}" }
    - { section: 'nova', option: 'auth_url', value: 'http://localhost:35357' }
    - { section: 'nova', option: 'auth_type', value: 'password' }
    - { section: 'nova', option: 'project_domain_name', value: 'default' }
    - { section: 'nova', option: 'user_domain_name', value: 'default' }
    - { section: 'nova', option: 'region_name', value: 'RegionOne' }
    - { section: 'nova', option: 'project_name', value: 'service' }
    - { section: 'nova', option: 'username', value: 'nova' }
    - { section: 'nova', option: 'password', value: "{{ serviceuser_password }}" }

- name: update ml2 plugin config file
  ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - { section: 'ml2', option: 'type_drivers', value: 'flat,vlan,vxlan' }
    - { section: 'ml2', option: 'tenant_network_types', value: 'vxlan' }
    - { section: 'ml2', option: 'mechanism_drivers', value: 'linuxbridge,l2population' }
    - { section: 'ml2', option: 'extension_drivers', value: 'port_security' }
    - { section: 'ml2_type_flat', option: 'flat_networks', value: 'provider' }
    - { section: 'ml2_type_vxlan', option: 'vni_ranges', value: '1:1000' }
    - { section: 'securitygroup', option: 'enable_ipset', value: 'True' }

- name: update linuxbridge config file
  ini_file: dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:          
    - { section: 'linux_bridge', option: 'physical_interface_mappings', value: 'provider:{{ interface_name }}' }
    - { section: 'vxlan', option: 'enable_vxlan', value: 'True' }
    - { section: 'vxlan', option: 'local_ip', value: "{{ controller_ipaddress }}" }
    - { section: 'vxlan', option: 'l2_population', value: 'True' }
    - { section: 'securitygroup', option: 'enable_security_group', value: 'True' }
    - { section: 'securitygroup', option: 'firewall_driver', value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver' }


- name: update l3 agent config file
  ini_file: dest=/etc/neutron/l3_agent.ini
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'interface_driver', value: 'neutron.agent.linux.interface.BridgeInterfaceDriver' }
    - { section: 'DEFAULT', option: 'external_network_bridge', value: '' }


- name: update dhcp config file
  ini_file: dest=/etc/neutron/dhcp_agent.ini
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'interface_driver', value: 'neutron.agent.linux.interface.BridgeInterfaceDriver' }
    - { section: 'DEFAULT', option: 'dhcp_driver', value: 'neutron.agent.linux.dhcp.Dnsmasq' }
    - { section: 'DEFAULT', option: 'enable_isolated_metadata', value: 'True' }


- name: update metadata config file
  ini_file: dest=/etc/neutron/metadata_agent.ini
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'nova_metadata_ip', value: 'localhost' }
    - { section: 'DEFAULT', option: 'metadata_proxy_shared_secret', value: "{{ metadata_secret }}" }


- name: update neutron details in nova config file
  ini_file: dest=/etc/nova/nova.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - { section: 'neutron', option: 'url', value: 'http://localhost:9696' }
    - { section: 'neutron', option: 'auth_url', value: 'http://localhost:35357' }
    - { section: 'neutron', option: 'auth_type', value: 'password' }
    - { section: 'neutron', option: 'project_domain_name', value: 'default' }
    - { section: 'neutron', option: 'user_domain_name', value: 'default' }
    - { section: 'neutron', option: 'region_name', value: 'RegionOne' }
    - { section: 'neutron', option: 'project_name', value: 'service' }
    - { section: 'neutron', option: 'username', value: 'neutron' }
    - { section: 'neutron', option: 'password', value: "{{ serviceuser_password }}" }
    - { section: 'neutron', option: 'service_metadata_proxy', value: 'True' }
    - { section: 'neutron', option: 'metadata_proxy_shared_secret', value: "{{ metadata_secret }}" }

- name: sync the neutron database
  command: /bin/su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron

- name: restat nova and neutron service on the node
  service: name={{ item }} state=restarted
  with_items:
    - nova-api
    - nova-compute
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
